---
- name: "APT: Install required packages"
  ansible.builtin.apt:
    pkg:
      - radosgw
    state: present

- name: "RGW zone creation and verification"
  include_tasks: "ceph-rgw-zone.yml"
  run_once: true

- name: "Check to see if rgw configuration exists"
  stat:
    path: "/var/lib/ceph/radosgw/ceph-rgw.{{ inventory_hostname|split('.')|first }}"
  register: ceph_rgw_configured

- name: "RGW add"
  include_tasks: "ceph-rgw-add.yml"
  when: not ceph_rgw_configured.stat.exists

- name: "Ensure ceph-radosgw is enabled and started"
  service:
    name: "ceph-radosgw@rgw.{{ inventory_hostname | split('.') | first }}"
    state: started
    enabled: true

- name: "UFW: Allow ceph rgw traffic"
  community.general.ufw:
    rule: allow
    port: "{{ ceph_rgw['port'] | default(7480) }}"
    proto: tcp
