---
- name: Create rgw data directory
  ansible.builtin.file:
    path: "/var/lib/ceph/radosgw/ceph-rgw.{{ inventory_hostname | split('.') | first }}"
    owner: ceph
    state: directory

- name: Fetch the keyring
  ansible.builtin.shell: "ceph auth get-or-create client.rgw.`hostname -s` osd 'allow rwx' mon 'allow rwx' -o /var/lib/ceph/radosgw/ceph-rgw.{{ inventory_hostname|split('.')|first
    }}/keyring"
- name: Set the keyring file permissions
  ansible.builtin.file:
    path: "/var/lib/ceph/radosgw/ceph-rgw.{{ inventory_hostname | split('.') | first }}/keyring"
    owner: ceph
    group: ceph
